version: '3.8'
services:
  thai-model-api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./qwen_thai_lora:/app/qwen_thai_lora:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # Requires nvidia-docker