# Thai Model Training Configuration
# =================================

# Model Settings
model:
  base_model: "Qwen/Qwen2.5-1.5B-Instruct"
  output_dir: "./models/checkpoints"
  
# LoRA Configuration
lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

# Training Parameters
training:
  # Epochs and steps
  num_train_epochs: 3
  max_steps: -1  # -1 means use num_train_epochs
  
  # Batch sizes
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  
  # Learning rate
  learning_rate: 2.0e-4
  warmup_steps: 100
  lr_scheduler_type: "linear"
  
  # Optimization
  optim: "paged_adamw_32bit"
  weight_decay: 0.001
  max_grad_norm: 0.3
  
  # Precision
  fp16: true
  bf16: false
  
  # Memory optimization
  gradient_checkpointing: true
  dataloader_num_workers: 4
  remove_unused_columns: false

# Dataset Configuration
dataset:
  name: "pythainlp/thaisum"
  train_split: "train"
  eval_split: "validation"
  max_seq_length: 1024
  preprocessing_num_workers: 4

# Evaluation
evaluation:
  eval_strategy: "steps"
  eval_steps: 200
  eval_accumulation_steps: 1
  load_best_model_at_end: false

# Logging and Saving
logging:
  logging_strategy: "steps"
  logging_steps: 50
  save_strategy: "steps"
  save_steps: 200
  save_total_limit: 3
  report_to: null  # ["tensorboard", "wandb"] or null

# Hardware Settings
hardware:
  use_cpu: false
  dataloader_pin_memory: false